## Numpy
<hr>


### Numpy Arrays

In [1]:
import numpy as np

In [3]:
my_list = [1,2,3]

In [6]:
arr = np.array(my_list)

arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Ways to create numpy arrays

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [119]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [121]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [12]:
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [14]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [15]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [17]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [117]:
np.ones(10) * 5

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

#### Linspace: It created equal distance points between the first two arguments based on the third arguments

In [20]:
np.linspace(0,5,5)  

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ])

In [21]:
np.linspace(0,5,6)

array([ 0.,  1.,  2.,  3.,  4.,  5.])

In [23]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [131]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])

#### Identity matrix

In [24]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [123]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Array of random values

In [41]:
np.random.rand(5)

array([ 0.30769398,  0.53991058,  0.11258481,  0.18434604,  0.58814012])

In [124]:
np.random.rand(1)

array([ 0.53674036])

In [42]:
np.random.rand(5,5)

array([[ 0.26343256,  0.51072078,  0.18323362,  0.31783331,  0.64043273],
       [ 0.90300916,  0.80708499,  0.8280753 ,  0.36776642,  0.43163701],
       [ 0.40724177,  0.30054079,  0.60277925,  0.57602275,  0.49573853],
       [ 0.8475628 ,  0.79735621,  0.84853349,  0.59213508,  0.53455355],
       [ 0.17747819,  0.06541901,  0.49125161,  0.56140091,  0.04674142]])

In [43]:
np.random.randn(2)

array([-0.37246713,  1.86083116])

In [44]:
np.random.randn(2,3)

array([[-0.35489404, -1.44548567, -0.39877665],
       [ 0.07614834,  0.19450659,  3.11066526]])

In [125]:
np.random.randn(25)

array([ 1.07023732,  1.15267057,  0.44512226, -0.79661377,  1.78253795,
        0.21795072, -0.50969593,  0.67962571,  0.24092202,  0.5059217 ,
        0.69497541,  2.60005991,  0.44463129,  1.65540599, -0.21662328,
        1.26186921, -1.86615839,  0.09779659,  0.35713091,  1.39659372,
        1.64472988,  1.09008867, -0.42940035, -0.97776737, -1.2425103 ])

In [46]:
np.random.randint(1, 100)

46

In [47]:
np.random.randint(1,100,10)

array([72, 16, 63, 13, 95, 91, 14, 29, 42, 26])

In [49]:
arr = np.arange(25)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [51]:
ranarr = np.random.randint(0,50,10)

ranarr

array([42, 21, 41, 41, 18, 31, 16, 16, 12, 31])

#### Few useful methods

In [52]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [53]:
ranarr.max()

42

In [54]:
ranarr.min()

12

In [55]:
ranarr.argmax()

0

In [56]:
ranarr.argmin()

8

In [57]:
arr.shape

(25,)

In [58]:
r = arr.reshape(5,5)

r.shape

(5, 5)

In [59]:
arr.dtype

dtype('int32')

In [122]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
np.linspace(0.01,1, 100).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

### Numpy Indexing and Selection

In [61]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[8]

8

In [63]:
arr[1:5]

array([1, 2, 3, 4])

In [64]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [65]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[:5] = 100

arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [68]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr = arr[:6]

slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_of_arr[:] = 99

slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [72]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [73]:
arr_copy = arr.copy()

arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy[:] = 100

arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [78]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing 2 D arrays

In [80]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [81]:
arr_2d[0]

array([ 5, 10, 15])

In [82]:
arr_2d[0][1]

10

In [83]:
arr_2d[0, 1]

10

In [84]:
arr_2d[1,2]

30

In [85]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [87]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [134]:
m = np.arange(1,26).reshape(5,5)

m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [135]:
m[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [136]:
m[3, 4]

20

In [137]:
m[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [138]:
m[4]

array([21, 22, 23, 24, 25])

In [139]:
m[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Selection

In [88]:
arr = np.arange(1,11)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
bool_arr = arr > 5

bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [91]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [92]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr<3]

array([1, 2])

In [95]:
arr_2d = np.arange(50).reshape(5, 10)

arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [96]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

### Numpy Operations
1. Array with Array
2. Array with Scalars
3. Universal Array Functions

In [98]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [100]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [101]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [102]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [103]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [104]:
1/0

ZeroDivisionError: division by zero

In [105]:
arr / arr

/home/adhish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [106]:
1 / arr

/home/adhish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [107]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [108]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [109]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [110]:
np.max(arr)

10

In [111]:
arr.max()

10

In [112]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [113]:
np.log(arr)

/home/adhish/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

In [140]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [141]:
m.sum()

325

In [142]:
m.std()

7.2111025509279782

In [143]:
m.sum(axis=0)

array([55, 60, 65, 70, 75])